### ISSUE TITLE
Bug in MADE sampling implementation in 'hw1_solutions.ipynb'

### ISSUE THREAD

**Issue by cr7legend** [rll/deepul#10]
//Implementation provided in the notebook  

![bug](https://user-images.githubusercontent.com/46714908/100797126-a033be00-3447-11eb-953b-73e2c8dc813e.png)

Suppose there are three variables x1,x2,x3 and the ordering given is 3,1,2 , then during sampling:
I)Desired sampling order should be x2,x3,x1
II)The above code sample in order x3,x1,x2

This bug is noticeable when random permutation is passed as ordering in function q2_b (passing ordering = None doesn't expose the bug):
model = MADE((1, H, W), 2, hidden_size=[512, 512],ordering = np.random.permutation(H*W)).cuda()

Result with the current bug on shape and MNIST samples (when ordering passed is random permutation)
![shapebug](https://user-images.githubusercontent.com/46714908/100797703-93fc3080-3448-11eb-999c-2453c89c19f3.png)
![mnistbug](https://user-images.githubusercontent.com/46714908/100797709-9494c700-3448-11eb-8533-02644e2b649d.png)

So the slide 38  of Lecture 2 also needs to be edited.Random permutation doesn't generate such bad samples as shown in slides.Its the bug in the code
https://docs.google.com/presentation/d/1xl4KKNYw08PatORSnFDyzX6MT98brEdYElZKZ5bi2YM/edit#slide=id.g7d02b18e4d_0_191

Suggested Fix code:
![correct_code](https://user-images.githubusercontent.com/46714908/100798152-3b796300-3449-11eb-9889-6770001443e1.png)

Results with this code
![shapes_correct](https://user-images.githubusercontent.com/46714908/100798312-7f6c6800-3449-11eb-8f67-69c7389e18f2.png)
![mnist_correct](https://user-images.githubusercontent.com/46714908/100798318-81cec200-3449-11eb-91e8-683cbfdf20de.png)

**Comment by wilson1yan** [comment]
Nice catch, thanks for letting us know about this! The homework solutions, demos, and slides should all be updated with the correct code / samples now
